export const LOAD_PODCAST_EPISODE = 'LOAD_PODCAST_EPISODE';
export const ADD_PODCASTS = 'ADD_PODCASTS';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const DELETE_FROM_PLAYLIST = 'DELETE_FROM_PLAYLIST';
